[tasks.dev]
alias = "dev"
description = "Start web development server"
run = "pnpm dev"
depends = [
  "//:pnpm-install",
  "//:sdk-generate",
]

[tasks.build]
description = "Build web"
run = "pnpm build"
depends = [
  "//:pnpm-install",
  "//:sdk-generate",
]

[tasks.start]
description = "Start web"
run = "pnpm start"
depends = [
  "//:pnpm-install",
  "//:sdk-generate",
]